### ISSUE TITLE
usename parameter parsing error

### ISSUE THREAD

**Issue by painsAgains** [erev0s/VAmPI#38]
The usename parameter requires a string type value, but when characters containing special characters are passed in, a response with a 500 response code is received
### API PATH
```
/user/v1/{username}
```
### Method
GET

### Example
curl  http://localhost:5000/users/v1/'jp#>2Q&h

**Comment by Sheryx00** [comment]
@PainsAgains, the error you are getting occurs because the database cannot process the query.

You are probably running the application with the vulnerable variable as True.

Remember that the main idea of this project is to make it a vulnerable application. Sanitizing the user input would make it difficult to perform SQL injections, which is what this endpoint was designed for.

In any case, how do you suggest improving it?
