### ISSUE TITLE
More features!

### ISSUE THREAD

**Issue by shizzgar** [erev0s/VAmPI#42]
First of all, man, your work is awesome!
I'm using it to teach my students how to make web more secured.

I want to advise some ides, what can be used in continuation of your fantastic project:

What about adding some kind of RCE and docker container hardening?
For example, your awesome app can started as container inside VM in 4 variants:
1. Vulnerable APP + Vulnerable container, including RCE and non hardened docker container = RCE -> docker escape on VM
2. Vulnerable APP + Not Vulnerable container, including RCE and hardened docker container = RCE, but no docker escape on VM
3. Not Vulnerable APP + Vulnerable container, no RCE and hardened docker container = no docker escape, but container may be DOSed.
4. Not Vulnerable APP + Not Vulnerable container, no RCE and hardened docker container = All Ok!

According to this:
https://github.com/OWASP/Docker-Security
https://github.com/OWASP/Docker-Security/blob/main/dist/owasp-docker-security.pdf
https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html

**Comment by erev0s** [comment]
hi @shizzgar 
really happy to see that the Vampi is helping creating a more secure web.
Your suggestions although they are really valuable in the context of web security, I am afraid they are slightly outside of the scope of this project. The RCE could arguably be added, while the reason it is not there already, is because it is not within the top 10 of OWASP in APIs.
If you believe the RCE can be helpful, ofc feel free to do a contribution to the project.
Will close this for now.
